### ISSUE TITLE
Destination Card bug

### ISSUE THREAD

**Issue by autumnm3** [cs340tabyu/cs340Fall2017#10]
I started a game with two players and did not receive the option to draw my initial destination cards, it was my turn so I went to draw destination cards and got toasted "you are drawing destination cards" but never had the little destination card window pop up.

I tried to draw train cards instead and each time I clicked a train card it toasted "you are drawing destination cards"

There were no history messages about drawing destination cards.

**Comment by emma-hunt** [comment]
I also had this bug when it was my turn first
