### ISSUE TITLE
Game is slow to respond and difficult to navigate

### ISSUE THREAD

**Issue by JaredsRydalch** [cs340tabyu/cs340Fall2017#101]
Players on physical devices instead of emulators had a very laggy experience with significant (1-2 second) delays between actions and seeing the UI update. Moving the game map around was unresponsive and slow, but possible.

**Comment by JaredsRydalch** [comment]
This may be due to the pixel count of the device/The resolution of the images

**Comment by litsters** [comment]
This is due to the high number of images used, not a flaw in the program.  The game should be run on emulators.  On some devices it will play better than others; performance was not in the spec.
