### ISSUE TITLE
Claimed routes are difficult to see

### ISSUE THREAD

**Issue by JaredsRydalch** [cs340tabyu/cs340Fall2017#102]
Claimed routes are a pastel color related to the player's color, but the difference is difficult to determine, possible to switch it so that claimed routes are vibrant and un-claimed are pastel?

**Comment by rpenfold** [comment]
There was a bug in the method for changing color that was causing claimed routes to not display correctly. That is now fixed, and non-claimed route colors have been updated to be less saturated.
