### ISSUE TITLE
Can join game twice

### ISSUE THREAD

**Issue by scottcrossen** [cs340tabyu/cs340Fall2017#108]
When application is exited, the game can be re-joined with the same user.

![screenshot_1511291623](https://user-images.githubusercontent.com/19987655/33091914-bc452ba6-ceb5-11e7-9d90-46a48b3a0d64.png)

**Comment by JaredsRydalch** [comment]
Fixed. Server now checks for duplicate usernames and denies a user joining twice (originally supported but this would cause problems in phase 4 especially)
