### ISSUE TITLE
View to see destination cards is not scrollable, can't see destination cards

### ISSUE THREAD

**Issue by cadedaniel** [cs340tabyu/cs340Fall2017#109]
can't see destination cards when we choose which ones to return.

<img width="1130" alt="screen shot 2017-11-21 at 12 19 05 pm" src="https://user-images.githubusercontent.com/950914/33092057-3682635c-ceb6-11e7-8894-f5932f8c4dd2.png">

**Comment by dylanmrowe** [comment]
Our game is only playable on tablet, pretty sure this is a reasonable requirement. I've seen app store games with tablet requirements

**Comment by dylanmrowe** [comment]
I'm closing this for now, along with the other tablet-requiring bug. I've played well-established games that were only available for tablet.
