### ISSUE TITLE
Game only works with 5 people

### ISSUE THREAD

**Issue by 1kstocks** [cs340tabyu/cs340Fall2017#111]

**Comment by mmartindale** [comment]
if you start game with 5 players, it will start game properly, but with 2 3 or 4 players, it will just say "not all destination cards are chosen" or something like that. update: also with 1 player you can start game but it does the same thing

**Comment by cadedaniel** [comment]
@1kstocks @mmartindale can you give more details? we are unable to reproduce

**Comment by wunter8** [comment]
Part of Phase 4 requirements
