### ISSUE TITLE
Creating multiple 2 player games simultaneously causes issues in starting the game

### ISSUE THREAD

**Issue by JaredsRydalch** [cs340tabyu/cs340Fall2017#112]
Creating multiple 2 player games (possibly multiple games in general) causes some game lobbies to show that a player has joined multiple games simultaneously, e.g. Player1 creates a 2 player game, Player2 creates a 2 player game, Player3 joins Player2's game and shows up in Player1's game as well, but the game does not start for Player1. If a Player4 were to join Player1's game, it starts for Player4 and not Player1.

**Comment by litsters** [comment]
Could not reproduce.
