### ISSUE TITLE
Opening the owned destination card dialog and attempting to draw destination cards for the second time crashes the game

### ISSUE THREAD

**Issue by JaredsRydalch** [cs340tabyu/cs340Fall2017#118]
Opening the owned destination card dialog and attempting to draw destination cards for the second time crashes the game. Any player can do this, regardless of the turn. The destination card selection dialog shows up with 3 blank destination cards. If all are selected to keep, the dialog closes with no issue, but if any is unselected (e.g. to be sent back to the server) the game crashes.

**Comment by rpenfold** [comment]
This was related to a bug in changing player state after turn was over. I just pushed the fix to master
