### ISSUE TITLE
map drawing cut off

### ISSUE THREAD

**Issue by nathansc92** [cs340tabyu/cs340Fall2017#127]
In portrait mode, right hand of screen draws incorrectly only on some devices (maybe a screen resolution issue?)

![image](https://user-images.githubusercontent.com/1480210/33092973-ef6c02c2-ceb8-11e7-9b6b-698895bedd91.png)

**Comment by nathansc92** [comment]
Bottom of map doesn’t draw correctly in landscape and us map is stretched weird

**Comment by scottcrossen** [comment]
What do "Some Devices" include? Was this tested on a Nexus 5X as per the README documentation?

**Comment by scottcrossen** [comment]
Seth says this is closed.
