### ISSUE TITLE
Game gets out of sync

### ISSUE THREAD

**Issue by planemaniac** [cs340tabyu/cs340Fall2017#130]
- Whose turn it is doesn't match up
- One player crashed every time he went to PlayerInfo tab (was the first player)
- Possible for everyone to think it's someone else's turn, no-one can do anything

_This was mostly when we had all rejoined the game, didn't have most of these issues on fresh game_

**Comment by scottcrossen** [comment]
Does player turn not match-up across devices or just between a player's "input-blocking" and the indication? If across devices, how isolated is it? Does only one device not match (if so which one) or does every device show something different?

Did other people try being first-player and see a crash on playerinfo tab as well or was it just isolated to the one user whenever he was first player (and thus probably related to his platform / emulation / connection or something?)

Game re-joining is a known issue and is selected for development. It is very likely that these issues will occur after the game is rejoined.

**Comment by scottcrossen** [comment]
These bugs were probably fixed with the latest patch. What I still don't know enough to test on is point (2).
