### ISSUE TITLE
no indication of player colors

### ISSUE THREAD

**Issue by MarchyMarch** [cs340tabyu/cs340Fall2017#140]

**Comment by scottcrossen** [comment]
Player colors are used when drawing routes. Did assignment specifications say we needed to list them elsewhere? I'm not trying to be contrary, I'm merely sticking to the minimalist project guidelines when it comes to issues. If this is a feature request we can of course do that as well. (though not as high priority)

**Comment by scottcrossen** [comment]
Seth says this is closed.
