### ISSUE TITLE
Issues Claiming Routes

### ISSUE THREAD

**Issue by planemaniac** [cs340tabyu/cs340Fall2017#142]
- Couldn't claim route with sufficient cards. Tried multiple routes, got "can't claim route" toast
- "My turn -> Click on a route -> choose color -> click ok -> no error, nothing changed on screen (showing that the route was claimed on the map), doesn’t change to next person’s turn on my device, but I try to choose cards and it says it’s not my turn" (only once)

**Comment by scottcrossen** [comment]
Was this route claimed on other people's screens?
Did  the turn increment after it said it wasn't your turn?
Was it only your device that experienced any error?
Did you have enough resource cards?
Was there anything different about the game when this occured that may have contributed to the problem?
Were the cards claimed after you clicked on them even though they showed an error toast?
