### ISSUE TITLE
sometimes there is a turn desync

### ISSUE THREAD

**Issue by MarchyMarch** [cs340tabyu/cs340Fall2017#147]
it seems like sometimes a player gets skipped.

**Comment by scottcrossen** [comment]
Was there any underlying conditions that were correlated with the issue? We need a better starting point to address this problem.

**Comment by scottcrossen** [comment]
The turn-system was overhauled. Skipping may occur when players logout now only. Closing unless further information is provided to justify how the player was skipped.
