### ISSUE TITLE
When deck runs out fills with with wilds and then you can keep taking

### ISSUE THREAD

**Issue by kadenbarlow** [cs340tabyu/cs340Fall2017#16]
When the deck runs out of cards, it just replaces everything with wild cards. I'm not sure if that's okay or not?

**Comment by emenden** [comment]
I have recreated this error. When no more deck cards and all train yard cards are wild, they keep replacing with wild. When down deck goes to 0, increases to 2 when you go to draw train cards.

**Comment by emenden** [comment]
This issue has been fixed.
