### ISSUE TITLE
Unmet destination points didn't add up correctly

### ISSUE THREAD

**Issue by kadenbarlow** [cs340tabyu/cs340Fall2017#22]
Finished one destination, but subtracted more than the points for the one I didn't finish

**Comment by pbstrein** [comment]
Do you remember which destination card it was? There were some errors on 3 destination cards that are now fixed. And by "subtracted more than the points for the one I didn't finish," what do you mean? I'm confused.... All the points have been adding up correctly now, did some card remove more points than the card had?
