### ISSUE TITLE
Points are doubled for player who claims a route then every other player gets points for the routes as well and ALL players have cars taken away

### ISSUE THREAD

**Issue by Mahallon** [cs340tabyu/cs340Fall2017#232]

**Comment by mitchell-foote** [comment]
What?

**Comment by Mahallon** [comment]
I know right? weird. but this is for the points up in the top right hand corner. On the points tab its correct for the opposing players.

**Comment by Mahallon** [comment]
So "cards" in the title of this issue should be "cars". their cars can go negative up in the top right hand corner where it shows the player stats
