### ISSUE TITLE
Cannot Register/login to play

### ISSUE THREAD

**Issue by jbrunner92** [cs340tabyu/cs340Fall2017#297]
![screen shot 2017-11-22 at 10 51 42 am](https://user-images.githubusercontent.com/10749662/33142307-3566588a-cf73-11e7-82e4-65a2b16b4582.png)
I can't get passed the login/register screen. I entered the appropriate IP address, portnumber, and then filled out my info to register. When I click the "Register" button, it doesn't do anything. I tried hitting the "Login" button in case it registered me, but doesn't take me to the lobby, but neither worked. The app eventually just crashed

**Comment by drmercer** [comment]
Looks like connection timeout. Probably a network setup problem; maybe the LAN had client isolation on, or something else to that effect. I motion we close this.

**Comment by jbrunner92** [comment]
Yeah, There was an issue with my computer connecting to my router due to an overload of devices connected to the internet at the time
