### ISSUE TITLE
Game stops allowing me to do anything when it is my turn

### ISSUE THREAD

**Issue by aarowhead** [cs340tabyu/cs340Fall2017#325]
A little ways into the game the game will say it is my turn but won't let me do anything. When I do an action the toast say it as if it worked but then it doesn't update any deck number or anything.

**Comment by drmercer** [comment]
@conman124 I wonder if this is related to the issue we saw, where the turn indicator didn't update. Could also be an issue with the poller being stuck.

**Comment by conman124** [comment]
Yeah, my guess is the indicator maybe didn't update, making it seem like it
was still aarowhead's turn when it actually wasn't.

**Comment by drmercer** [comment]
Could not reproduce. Closing.
