### ISSUE TITLE
Navigation bar makes sliding the drawer out difficult

### ISSUE THREAD

**Issue by mogard** [cs340tabyu/cs340Fall2017#33]
Consider using a tab to make it easier

**Comment by MangoMoe** [comment]
This is a real issue for me playing the game... Like 90% of the time I can't get the drawer to slide out.

**Comment by drmercer** [comment]
This should be improved. Until then here's a temporary fix:

![git gud](https://funnypictures3.fjcdn.com/thumbnails/comments/Blank+_908c6484e181745e1e70c618cd7455d2.jpg)

:wink:
