### ISSUE TITLE
Train Cards don't Update Between Players Immediately.

### ISSUE THREAD

**Issue by WestRyanK** [cs340tabyu/cs340Fall2017#50]
When one player draws a card and the face up cards are updated it is only reflected in the client that drew the train card. The train cards are updated in the other clients if they try to draw a train card though.

**Comment by WestRyanK** [comment]
This happens always if on the first turn a player picks train cards from face up pile.
If we try to pick one of the cards that didn't update, it will crash the client

**Comment by WestRyanK** [comment]
![image](https://user-images.githubusercontent.com/5795155/33090269-9cb0a34c-ceb0-11e7-9f8c-8378baf1619a.png)

**Comment by jacobez** [comment]
This was my screen:

![screenshot_1511289687](https://user-images.githubusercontent.com/31745594/33090909-c85292f6-ceb2-11e7-84fd-810a36e626c4.png)
