### ISSUE TITLE
Hard to tell who's turn it is

### ISSUE THREAD

**Issue by pspenc** [cs340tabyu/cs340Fall2017#66]
Your name changing to red is hard to recognize, especially if the streak above your name is red, you just assume you are red and not that red means its your turn. Maybe have the names be the color of the player, and the streak moves between players for their turns?

**Comment by WestRyanK** [comment]
Altered the visuals for current turn. Instead of just highlighting the user's name, it highlights their stats as well. So there is more of a color change
![image](https://user-images.githubusercontent.com/5795155/33113665-ab24229e-cf16-11e7-9b1d-03ea16ac8a29.png)
