### ISSUE TITLE
Closing Server

### ISSUE THREAD

**Issue by washa3** [cs340tabyu/cs340Fall2017#81]
Closing the Server while in the Login Screen (after having logged in and gone back (using back button)) crashed the app.

**Comment by washa3** [comment]
For clarification--the Android back button

**Comment by washa3** [comment]
This was also done a SINGLE player in the game

**Comment by cadedaniel** [comment]
Did you find this by killing the server process? or just pressing the android back button?

**Comment by washa3** [comment]
Killing the Server Process. Also, this occurs ANYTIME we close the server, not just in this particular instance

**Comment by wunter8** [comment]
Part of Phase 4 requirements
