### ISSUE TITLE
Drawing the first three cards and Destination Cards

### ISSUE THREAD

**Issue by washa3** [cs340tabyu/cs340Fall2017#85]
It allowed us to draw only one destination card (for the game setup). The game rules state that you have to draw at least 2 of the 3 destination cards served

**Comment by washa3** [comment]
Looking at further effects of this, the Destination Card Deck had 32 cards (max is 30) based on what happened, it should have had 27 cards in it, and 2 cards discarded

**Comment by mmartindale** [comment]
this card number is also not being updated anywhere, so it has permanently been 32, with 5 people in the game, all clients are the same.

**Comment by torstein-collett** [comment]
the first three cards drawn by players do not come out of the deck properly
after drawing all cards I had 33
