### ISSUE TITLE
Leaving and re-Joining leaves "Ghost Players" in UI

### ISSUE THREAD

**Issue by JaredsRydalch** [cs340tabyu/cs340Fall2017#94]
Joining a game and leaving and then re-joining a game while other players are joined creates a duplicate player on all other player's devices in the UI, but does not start the game. E.g. If I am PlayerNumber and I join and leave and join 5 times in a 3 player game with 1 other player, I will see the game before I join it as 1/3, and when I join I will see it at 2/3, but the other player in the game will see 7/3 or more, all duplicate players.

**Comment by rpenfold** [comment]
resolved
